// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGneEGHNepCIbFtKVxEq4pTLTTi_I4Dwg',
    appId: '1:842974457872:web:dceedb7da65c56dcb49a95',
    messagingSenderId: '842974457872',
    projectId: 'des3113-task-manager',
    authDomain: 'des3113-task-manager.firebaseapp.com',
    storageBucket: 'des3113-task-manager.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDLb91ANLkWMLw3_-eol8_e3TPkYmYQbFk',
    appId: '1:842974457872:android:27ba34d37c19b508b49a95',
    messagingSenderId: '842974457872',
    projectId: 'des3113-task-manager',
    storageBucket: 'des3113-task-manager.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA9UGoSVe02GNcq-KmQyIMq1FBxaZDVWIc',
    appId: '1:842974457872:ios:9eddc270bb0a1e7ab49a95',
    messagingSenderId: '842974457872',
    projectId: 'des3113-task-manager',
    storageBucket: 'des3113-task-manager.firebasestorage.app',
    iosBundleId: 'com.example.myTaskManager',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA9UGoSVe02GNcq-KmQyIMq1FBxaZDVWIc',
    appId: '1:842974457872:ios:9eddc270bb0a1e7ab49a95',
    messagingSenderId: '842974457872',
    projectId: 'des3113-task-manager',
    storageBucket: 'des3113-task-manager.firebasestorage.app',
    iosBundleId: 'com.example.myTaskManager',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCGneEGHNepCIbFtKVxEq4pTLTTi_I4Dwg',
    appId: '1:842974457872:web:4d4d5143ff6529beb49a95',
    messagingSenderId: '842974457872',
    projectId: 'des3113-task-manager',
    authDomain: 'des3113-task-manager.firebaseapp.com',
    storageBucket: 'des3113-task-manager.firebasestorage.app',
  );
}
